apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-tripviewer-img
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer-container
        image: registrybwj5358.azurecr.io/tripviewer:1.0
        env:
        - name: SQL_USER
          value: "sqladminbWj5358"
        - name: SQL_PASSWORD
          value: "bN1uq3Fc9"
        - name: SQL_SERVER
          value: "sqlserverbwj5358.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  type: ClusterIP
  selector:
    app: tripviewer
  ports:
    - protocol: TCP
      port: 80